name: compute-exchange

services:
  app:
    image: ghcr.io/dylan-nihilo/compute-exchange:${IMAGE_TAG:-latest}
    container_name: compute-exchange
    restart: unless-stopped
    environment:
      HOSTNAME: 0.0.0.0
      NODE_ENV: production
      PORT: "3000"
    networks:
      - tea-network

networks:
  tea-network:
    external: true
    name: deploy_tea-network
