"""Rebuild Landing-only WOFF2 subsets without changing outlines or hinting.

uv run --with 'fonttools[woff]==4.56.0' python scripts/subset-landing-fonts.py [--check]
"""
import hashlib
import io
from pathlib import Path
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCES = sorted((ROOT / 'src/components/landing').rglob('*.tsx')) + [
    ROOT / 'src/components/landing/hero/content.ts',
]
# Include all source characters to cover static copy without a fragile JSX parser.
characters = set(''.join(chr(c) for c in range(32, 127)))
for source in SOURCES:
    characters.update(c for c in source.read_text() if not c.isspace())
codepoints = sorted(map(ord, characters))
css = ['/* Generated by scripts/subset-landing-fonts.py; do not edit. */']
total = 0
for weight, source in [(500, 'AlibabaPuHuiTi-2-65-Medium.woff2'), (600, 'AlibabaPuHuiTi-2-75-SemiBold.woff2')]:
    font = TTFont(ROOT / 'public/fonts' / source, recalcTimestamp=False)
    original_cmap = font.getBestCmap()
    covered = sorted(set(codepoints) & original_cmap.keys())
    options = subset.Options()
    options.layout_features = ['*']
    options.name_IDs = ['*']
    options.name_languages = ['*']
    options.name_legacy = True
    processor = subset.Subsetter(options=options)
    processor.populate(unicodes=covered)
    processor.subset(font)
    assert set(font.getBestCmap()) == set(covered)
    buffer = io.BytesIO()
    font.save(buffer)
    data = buffer.getvalue()
    name = f'omnis-landing-{weight}-{hashlib.sha256(data).hexdigest()[:12]}.woff2'
    target = ROOT / 'public/fonts' / name
    if '--check' in sys.argv:
        assert target.exists() and target.read_bytes() == data, f'Regenerate {name}'
    else:
        target.write_bytes(data)
    total += len(data)
    ranges = ','.join(f'U+{value:X}' for value in covered)
    css.append(f'''@font-face {{
  font-family: "OmniS Landing";
  src: url("/fonts/{name}") format("woff2");
  font-weight: {weight};
  font-style: normal;
  font-display: swap;
  unicode-range: {ranges};
}}''')
    print(f'{name}: {len(data):,} bytes, {len(covered)} characters')
css.append('''.landing-page .font-display {
  font-family: "OmniS Landing", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif;
}''')
content = '\n\n'.join(css) + '\n'
target = ROOT / 'src/components/landing/fonts.css'
if '--check' in sys.argv:
    assert target.read_text() == content, 'Regenerate fonts.css after copy changes'
else:
    target.write_text(content)
print(f'Total: {total:,} bytes; original fonts and embedded copyright metadata retained')
